logo_title: 心向光明

style: black

favicon: /pig.ico

menu:
  作品: /project
  域名: /domain
  友联: /links
  关于: /about
  Github: https://github.com/zhachery

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: true